remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

title: Next Expense
description: Track and Manage your receipts for all types of expenses
show_downloads: false
google_analytics:
